allowBuilds:
  core-js: false
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.4'
  - '@biomejs/cli-darwin-arm64@2.5.4'
  - '@biomejs/cli-darwin-x64@2.5.4'
  - '@biomejs/cli-linux-arm64-musl@2.5.4'
  - '@biomejs/cli-linux-arm64@2.5.4'
  - '@biomejs/cli-linux-x64-musl@2.5.4'
  - '@biomejs/cli-linux-x64@2.5.4'
  - '@biomejs/cli-win32-arm64@2.5.4'
  - '@biomejs/cli-win32-x64@2.5.4'
  - '@biomejs/biome@2.5.5'
  - '@biomejs/cli-darwin-arm64@2.5.5'
  - '@biomejs/cli-darwin-x64@2.5.5'
  - '@biomejs/cli-linux-arm64-musl@2.5.5'
  - '@biomejs/cli-linux-arm64@2.5.5'
  - '@biomejs/cli-linux-x64-musl@2.5.5'
  - '@biomejs/cli-linux-x64@2.5.5'
  - '@biomejs/cli-win32-arm64@2.5.5'
  - '@biomejs/cli-win32-x64@2.5.5'
  - '@biomejs/biome@2.5.0'
  - '@biomejs/cli-darwin-arm64@2.5.0'
  - '@biomejs/cli-darwin-x64@2.5.0'
  - '@biomejs/cli-linux-arm64-musl@2.5.0'
  - '@biomejs/cli-linux-arm64@2.5.0'
  - '@biomejs/cli-linux-x64-musl@2.5.0'
  - '@biomejs/cli-linux-x64@2.5.0'
  - '@biomejs/cli-win32-arm64@2.5.0'
  - '@biomejs/cli-win32-x64@2.5.0'
  - '@biomejs/biome@2.5.3'
  - '@biomejs/cli-darwin-arm64@2.5.3'
  - '@biomejs/cli-darwin-x64@2.5.3'
  - '@biomejs/cli-linux-arm64-musl@2.5.3'
  - '@biomejs/cli-linux-arm64@2.5.3'
  - '@biomejs/cli-linux-x64-musl@2.5.3'
  - '@biomejs/cli-linux-x64@2.5.3'
  - '@biomejs/cli-win32-arm64@2.5.3'
  - '@biomejs/cli-win32-x64@2.5.3'
  - '@mui/core-downloads-tracker@9.1.2'
  - '@mui/material@9.1.2'
  - '@mui/private-theming@9.1.1'
  - '@mui/styled-engine@9.1.1'
  - '@mui/system@9.1.2'
  - '@mui/types@9.1.1'
  - '@mui/utils@9.1.1'
  - '@types/node@24.13.2'
  - '@types/node@24.13.3'
  - '@playwright/test@1.61.1'
  - playwright-core@1.61.1
  - playwright@1.61.1
  - react@19.2.7
  - react-dom@19.2.8
