allowBuilds:
  core-js: false
minimumReleaseAgeExclude:
  - '@mui/core-downloads-tracker@9.1.0'
  - '@mui/material@9.1.0'
  - '@mui/private-theming@9.1.0'
  - '@mui/styled-engine@9.1.0'
  - '@mui/system@9.1.0'
  - '@mui/utils@9.1.0'
  - '@types/node@24.13.2'
