version: "3"

includes:
  front: FrontTasks.yaml
  server: ServerTasks.yaml

tasks:
  default:
    aliases:
      - dev
    deps:
      - front:dev
      - server:dev

  preview:
    deps:
      - front:build
      - server:build
    cmds:
      - ./target/debug/release-date-sorterer

  e2e:
    cmds:
      - task e2e:dev
      - task e2e:preview

  e2e:dev:
    cmds:
      - docker compose up -d --build server web
      - docker compose up e2e-dev
      - docker compose stop server web

  e2e:preview:
    cmds:
      - docker compose up -d --build preview
      - while ! curl -s http://localhost:3000/api/health; do sleep 1; done
      - docker compose up e2e-preview
      - docker compose stop preview

  sqlx:
    deps:
      - server:sqlx

  lint:
    deps:
      - front:lint
      - server:lint
